version: '3.8'
services:
  app:
    container_name: resume-website
    image: yongjichen/resume-website
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    command: yarn start